const fs=require('fs'),vm=require('vm');let n=0;function ok(x,m){if(!x)throw new Error(m);n++}
const center=fs.readFileSync('js/intelligence/intelligence-center.js','utf8');
const idx=fs.readFileSync('index.html','utf8'),sw=fs.readFileSync('sw.js','utf8'),store=fs.readFileSync('js/ocr/ocr-model-store.js','utf8'),paddle=fs.readFileSync('js/ocr/paddle-engine.js','utf8'),off=fs.readFileSync('js/core/ocr-offline-readiness.js','utf8'),mm=fs.readFileSync('js/intelligence/recognition-model-manager.js','utf8'),cfg=fs.readFileSync('js/config/recognition-models.js','utf8');
ok(idx.includes('js/ocr/ocr-model-store.js'),'model store loaded');ok(sw.includes("'./js/ocr/ocr-model-store.js'"),'model store app shell');ok(sw.includes("jizhang-ocr-models-v1"),'model cache preserved');ok(sw.includes("/runtime-models/ocr/"),'runtime model fetch path');
ok(store.includes('OCR_MODEL_ASSET_CROSS_ORIGIN'),'same origin gate');ok(store.includes('OCR_MODEL_ASSET_HASH_INVALID'),'hash contract');ok(store.includes("CACHE+'-stage-'"),'atomic staging');ok(store.includes("CACHE+'-backup-'"),'rollback backup');ok(store.includes('OCR_MODEL_POST_INSTALL_HEALTH_FAILED'),'post install health');ok(store.includes('MIN_FREE_RESERVE'),'storage reserve');
ok(paddle.includes('ocrModelStore.runtimeConfig'),'paddle consumes installed package');ok(paddle.includes('textDetectionModelName')===false,'paddle does not hardcode package model names');
ok(off.includes('await modelState()'),'readiness health async');ok(off.includes('缓存缺失或完整性检查未通过'),'evicted cache not reported offline');ok(mm.includes('inspectOcr')&&mm.includes('installOcr')&&mm.includes('removeOcr'),'manager OCR lifecycle');ok(cfg.includes('paddleOcr'),'release slot');ok(center.includes('installOcrPackage')&&center.includes('完整性模型包'),'installer exposed in Intelligence Center');
const sandbox={URL,location:{href:'https://example.test/app/'},localStorage:{getItem(){return null},setItem(){},removeItem(){}},OcrKit:{},globalThis:null};sandbox.globalThis=sandbox;vm.createContext(sandbox);vm.runInContext(store,sandbox);let threw=false;try{sandbox.OcrKit.ocrModelStore.validateManifest({id:'x1',det:{name:'d',url:'https://evil.test/d.tar'},rec:{name:'r',url:'/runtime-models/ocr/r.tar'}})}catch(e){threw=String(e.message).includes('CROSS_ORIGIN')}ok(threw,'cross origin rejected at runtime');
const m=sandbox.OcrKit.ocrModelStore.validateManifest({id:'x1',det:{name:'d',url:'/runtime-models/ocr/d.tar',size:10,sha256:'a'.repeat(64)},rec:{name:'r',url:'/runtime-models/ocr/r.tar',size:20,sha256:'b'.repeat(64)}});ok(m.det.url.startsWith('https://example.test/'),'same origin normalized');
console.log('System Strength Round6:',n+'/19 PASS');
