const fs=require('fs'),assert=require('assert');
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('css/style.css','utf8');
const spec=fs.readFileSync('js/idphoto/spec-registry.js','utf8');
const gate=fs.readFileSync('js/idphoto/capture-quality-gate.js','utf8');
const studio=fs.readFileSync('js/idphoto/idphoto-studio.js','utf8');
let n=0; const ok=(x,m)=>{assert(x,m);n++};
ok(html.includes('page-idphoto'),'ID photo page missing');
ok(html.includes('data-page="idphoto"'),'ID photo nav missing');
ok(html.includes('mingxi-seal.png'),'seal asset missing from UI');
ok(!html.includes('<div class="logo-icon">📋</div>'),'old clipboard brand icon remains');
ok(spec.includes('registerPack'),'replaceable spec packs missing');
ok(spec.includes("region:'global'"),'global-first registry missing');
ok(!/region:'mx'|region:'mexico'/i.test(spec),'country hard-coded in core');
ok(gate.includes("'TOO_CLOSE'"),'too-close gate missing');
ok(gate.includes("'TOO_FAR'"),'too-far gate missing');
ok(gate.includes("'BLUR'"),'blur gate missing');
ok(gate.includes("'FACE_SHADOW'"),'shadow gate missing');
ok(gate.includes('effectiveFacePx'),'effective face resolution missing');
ok(studio.includes('analyzeImage'),'quality analysis not wired');
ok(html.includes('默认不上传照片'),'local privacy promise missing');
ok(html.includes('不会用 AI 虚构缺失的头顶/肩部'),'anti-fabrication rule missing');
ok(css.includes('.mingxi-seal'),'seal styling missing');
console.log(`V210 ID photo foundation: ${n}/16 PASS`);
