'use strict';
const fs=require('fs'), vm=require('vm'), assert=require('assert');
const ctx={globalThis:{}}; ctx.window=ctx.globalThis; vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/intelligence/transaction-core.js','utf8'),ctx);
const T=ctx.globalThis.JizhangIntelligence.TransactionCore;
let r=T.validate({type:'transfer',date:'2026-09-05',amount:10000,account:'BBVA',accountTo:'Santander'});
assert.equal(r.ok,true);
r=T.validate({type:'transfer',date:'2026-09-05',amount:10000,account:'BBVA',accountTo:'BBVA'}); assert.equal(r.ok,false);
r=T.validate({type:'purchase',date:'2026-09-05',amount:1000,paidAmount:1200}); assert(r.errors.includes('OVERPAID'));
assert.equal(T.decision(.4,false),'RETRY'); assert.equal(T.decision(.7,false),'CONFIRM'); assert.equal(T.decision(.9,false),'ACCEPT');
console.log('transaction-core: PASS');
let p=T.prepare('expense',{date:'2026-09-05',category:'房租',amount:'13500',account:'BBVA',payee:'房东',remark:'九月房租',currency:'mxn'},'manual');
assert.equal(p.ok,true); assert.equal(p.legacy.amount,13500); assert.equal(p.legacy.payee,'房东'); assert.equal(p.legacy.currency,'MXN');
p=T.prepare('purchase',{doc_date:'2026-09-05',supplier:'Proveedor',total_amount:'1000',paid_amount:'1001'},'manual');
assert.equal(p.ok,false); assert(p.errors.includes('OVERPAID'));
p=T.prepare('income',{date:'2026-09-05',project:'销售',amount:'500',account:'现金',confidence:73},'ocr');
assert.equal(p.decision,'CONFIRM'); assert.equal(p.transaction.confidence,0.73);
assert.equal(T.SCHEMA_VERSION,3);
console.log('transaction-core-v3: PASS');
