const fs=require('fs'),vm=require('vm'),assert=require('assert');
let passed=0; const ok=(cond,msg)=>{assert(cond,msg);passed++;console.log('✔ '+msg)};
const ctx={console,globalThis:null};ctx.globalThis=ctx;vm.createContext(ctx);
vm.runInContext(fs.readFileSync('js/voice/voice-parser.js','utf8'),ctx);
const V=ctx.VoiceKit;
ok(V.parseAmount('支出一晚三千元')===13000,'“晚”数字邻域恢复为万');
ok(V.parseAmount('收入2网5千元')===25000,'“网”数字邻域恢复为万');
ok(V.parseAmount('支出十五旺三千')===153000,'“旺”数字邻域恢复为万');
ok(V.parseAmount('支出一三千元')===13000,'V211 金额语法恢复漏“万”');
ok(V.amountScaleRisk('支出一三千元',13000).risk===false,'已被严格语法恢复的“万”不再制造二选一');
ok(V.amountConfidence(13000,'支出一三千元')>=0.8,'恢复后可进入唯一高置信金额');
ok(V.amountScaleRisk('支出一千三百元',1300).risk===false,'正常千级金额不误报');
ok(V.amountScaleRisk('支出一万三千元',13000).risk===false,'明确万单位不误报');
const css=fs.readFileSync('css/style.css','utf8');
ok(css.includes('--surface-feedback:')&&css.includes('--surface-feedback-error:'),'主题定义反馈层语义 token');
ok(css.includes('--kpi-income-bg:')&&css.includes('--kpi-networth-bg:'),'8类首页KPI走主题 token');
ok(css.includes('.toast.error { background: var(--surface-feedback-error)'),'错误提示随主题 token');
ok(!/\.income-card\s*\{\s*background:\s*linear-gradient\(135deg,\s*#fff8dc/m.test(css),'收入卡不再写死秋色背景');
const app=fs.readFileSync('js/app.js','utf8');
ok(!app.includes("t.style.background = type === 'error'"),'Toast JS 不再强制固定背景色');
ok(app.includes("t.classList.add(type === 'error' ? 'error' : 'success', 'show')"),'Toast 只设置语义状态');
const html=fs.readFileSync('index.html','utf8');
ok(html.includes('智能识别与模型管理')&&html.includes('打开语音 / OCR 模型管理'),'设置页提供明确模型管理入口');
const ic=fs.readFileSync('js/intelligence/intelligence-center.js','utf8');
ok(ic.includes('preloadOcrModels')&&ic.includes('安装 / 预加载 OCR'),'识别中心提供OCR显式安装/预加载入口');
const sw=fs.readFileSync('sw.js','utf8');
ok(/const CACHE_NAME = 'jizhang-pwa-[0-9a-f]{8}'/.test(sw),'Service Worker 使用构建内容哈希缓存命名空间');
console.log(`V209 recognition/theme integrity: ${passed}/${passed} PASS`);
