'use strict';
const fs=require('fs'),assert=require('assert'),path=require('path'),R=__dirname;
const read=p=>fs.readFileSync(path.join(R,p),'utf8');let n=0;const ok=(x,m)=>{assert(x,m);console.log('PASS',m);n++};
const life=read('js/personalization/pet-life-os.js'),engine=read('js/personalization/pet-engine.js'),dir=read('js/personalization/pet-director.js'),bus=read('js/personalization/app-event-bus.js'),html=read('index.html'),css=read('css/style.css'),sw=read('sw.js'),weather=read('js/weather/weather-service.js');
ok(/ROUTINES=\{/.test(life)&&/worker:\[/.test(life)&&/student:\[/.test(life),'真实时间作息模板已建立');
ok(/phaseAt\(d\)/.test(life)&&/nowMinutes/.test(life),'按真实时钟解析当前生活阶段');
ok(/variationMinutes/.test(life)&&/Math\.floor\(d\.getTime\(\)\//.test(life),'活动切换基于真实时间桶而非累计 interval');
ok(/MICRO=/.test(life)&&/coffee/.test(life)&&/bike/.test(life)&&/hike/.test(life)&&/bath/.test(life)&&/phone/.test(life),'生活微动作池覆盖咖啡/骑车/远足/洗澡/手机');
ok(/WEATHER_MOD/.test(life)&&/weatherKind/.test(life),'天气作为生活动作修饰器');
ok(/interrupt\(kind,label\)/.test(life)&&/resume\(\)/.test(life),'支持业务打断与恢复');
ok(/avoidRect/.test(engine)&&/visualViewport/.test(engine)&&/focusin/.test(life),'输入框与软键盘智能避让链路');
ok(/pointerdown/.test(engine)&&/pointermove/.test(engine)&&/moveTo/.test(engine),'宠物支持拖动与自由位置');
ok(/DIARY_KEY/.test(life)&&/MAX_DIARY/.test(life)&&/showDiary/.test(life),'轻量养成日记已实现并设上限');
ok(/petRoutine/.test(html)&&/petLifeInterval/.test(html)&&/petWeatherLink/.test(html)&&/petAvoidInputs/.test(html),'设置页暴露作息/频率/天气/避让');
ok(/pet-life-diary/.test(css)&&/pet-life-badge/.test(css),'Pet Life UI 样式已接入');
ok(/weather:context/.test(bus)&&/SmAppEvents\.emit\('weather:context'/.test(weather),'Weather Intelligence 经安全事件总线联动');
ok(/SmPetLifeOS\.interrupt/.test(dir)&&/SmPetLifeOS\.resume/.test(dir),'Pet Director 将业务事件交给 Life OS');
ok(sw.includes('./js/personalization/pet-life-os.js'),'Pet Life OS 离线预缓存');
ok(/VERSION:4/.test(engine)&&/VERSION:3/.test(dir)&&/VERSION:3/.test(bus)&&/VERSION:1/.test(life),'模块版本已推进');
console.log(`Pet Life OS Round1: ${n}/${n} PASS`);
