(function(g){'use strict';
const CFG_KEY='sm_pet_life_v1',DIARY_KEY='sm_pet_diary_v1',MAX_DIARY=720;
const ROUTINES={
 worker:[
  ['00:00','sleep','睡觉'],['06:50','wake','起床'],['07:00','wash','洗漱'],['07:20','breakfast','早餐'],['07:40','coffee','咖啡/茶'],['08:00','commute','出门上班'],['08:30','work','工作'],['12:30','lunch','午饭'],['13:10','rest','午休'],['14:00','work','工作'],['18:00','commute_home','下班回家'],['18:40','dinner','晚饭'],['19:30','leisure','晚间休闲'],['21:00','study_web','读书/上网'],['22:10','bath','洗澡'],['22:35','wash','刷牙洗脸'],['22:50','phone','刷手机'],['23:15','sleep','睡觉']],
 student:[
  ['00:00','sleep','睡觉'],['06:40','wake','起床'],['06:50','wash','洗漱'],['07:10','breakfast','早餐'],['07:40','commute','去上学'],['08:10','school','上课'],['12:10','lunch','午饭'],['12:50','rest','午休'],['13:30','school','上课'],['16:30','commute_home','放学回家'],['17:10','leisure','休息'],['18:20','dinner','晚饭'],['19:00','homework','做作业'],['20:40','leisure','看电视/上网'],['21:45','bath','洗澡'],['22:10','wash','刷牙洗脸'],['22:25','phone','刷手机'],['22:45','sleep','睡觉']],
 home:[
  ['00:00','sleep','睡觉'],['07:30','wake','起床'],['07:45','wash','洗漱'],['08:10','breakfast','早餐'],['08:40','coffee','喝茶/咖啡'],['09:00','work','居家工作'],['12:30','lunch','午饭'],['13:20','rest','午休'],['14:00','work','继续工作'],['17:30','leisure','散步/休闲'],['18:40','dinner','晚饭'],['19:30','leisure','看电视/刷手机'],['21:00','study_web','读书/上网'],['22:15','bath','洗澡'],['22:40','wash','洗漱'],['23:10','sleep','睡觉']],
 free:[
  ['00:00','sleep','睡觉'],['08:30','wake','起床'],['08:45','wash','洗漱'],['09:10','breakfast','早餐'],['09:40','coffee','咖啡/茶'],['10:00','creative','自由工作'],['12:40','lunch','午饭'],['13:30','rest','休息'],['14:10','creative','自由工作'],['17:00','outdoor','户外活动'],['19:00','dinner','晚饭'],['20:00','leisure','休闲'],['21:20','study_web','读书/上网'],['22:40','bath','洗澡'],['23:20','sleep','睡觉']]
};
const MICRO={
 wake:['stretch','lookaround','happy'],wash:['wash','brush'],breakfast:['eat','tea'],coffee:['coffee','tea'],commute:['walk','bike'],commute_home:['walk','bike'],work:['work','type','write','read','coffee','stretch'],school:['read','write','think'],lunch:['eat','tea'],rest:['rest','yawn','nap'],leisure:['tv','phone','read','tea','idle'],study_web:['read','web','write','phone'],homework:['write','read','think'],bath:['bath'],phone:['phone','idle'],creative:['work','write','web','read'],outdoor:['bike','hike','walk'],sleep:['sleep']
};
const WEATHER_MOD={rain:['umbrella','read','tea','tv'],wind:['windy','indoor','tea'],hot:['water','swim','indoor'],cold:['hot_tea','read','indoor'],clear:['walk','bike','hike']};
let cfg={enabled:true,routine:'worker',variationMinutes:60,natural:true,weather:true,avoidInputs:true,diary:true,weekendFree:true};
let runtime={scene:null,activity:null,interrupted:null,nextAt:0,timer:0,lastWeather:null};
function mins(s){const a=String(s).split(':').map(Number);return a[0]*60+a[1]}
function nowMinutes(d){return d.getHours()*60+d.getMinutes()}
function load(){try{Object.assign(cfg,JSON.parse(localStorage.getItem(CFG_KEY)||'{}'))}catch(e){}return cfg}
function save(){try{localStorage.setItem(CFG_KEY,JSON.stringify(cfg))}catch(e){}}
function routineFor(d){let name=cfg.routine;if(cfg.weekendFree&&(d.getDay()===0||d.getDay()===6))name='free';return ROUTINES[name]||ROUTINES.worker}
function phaseAt(d){const r=routineFor(d),m=nowMinutes(d);let p=r[0];for(const x of r){if(mins(x[0])<=m)p=x;else break}return {time:p[0],scene:p[1],label:p[2],routine:r===ROUTINES.free?'free':cfg.routine}}
function choose(arr,seed){if(!arr||!arr.length)return'idle';let n=Math.abs(Number(seed)||Date.now());return arr[n%arr.length]}
function weatherKind(){if(!cfg.weather)return null;try{const cur=g.WeatherKit&&g.WeatherKit.WeatherService&&g.WeatherKit.WeatherService.current();const data=cur&&cur.data,events=cur&&cur.events||[];if(events.some(e=>e.type==='rain'))return'rain';if(events.some(e=>e.type==='wind'))return'wind';const t=data&&data.current&&Number(data.current.apparentTemperature);if(Number.isFinite(t)&&t>=34)return'hot';if(Number.isFinite(t)&&t<=10)return'cold';if(data&&data.current&&Number(data.current.weatherCode)<=3)return'clear'}catch(e){}return null}
function pickActivity(scene,d){if(scene==='sleep')return'sleep';let pool=(MICRO[scene]||['idle']).slice(),wk=weatherKind();if(wk&&WEATHER_MOD[wk]){if(scene==='outdoor'&&['rain','wind','hot'].includes(wk))pool=WEATHER_MOD[wk].concat(['indoor','read']);else if(['leisure','commute','commute_home','coffee'].includes(scene))pool=pool.concat(WEATHER_MOD[wk])}const bucket=Math.floor(d.getTime()/(Math.max(15,Number(cfg.variationMinutes)||60)*60000));return choose(pool,bucket)}
function diary(){try{return JSON.parse(localStorage.getItem(DIARY_KEY)||'[]')}catch(e){return[]}}
function log(kind,label,meta){if(!cfg.diary)return;const a=diary(),prev=a[a.length-1];if(prev&&prev.kind===kind&&prev.label===label&&Date.now()-prev.at<5*60*1000)return;a.push({at:Date.now(),kind,label:String(label||'').slice(0,80),meta:meta&&meta.weather?{weather:meta.weather}:undefined});while(a.length>MAX_DIARY)a.shift();try{localStorage.setItem(DIARY_KEY,JSON.stringify(a))}catch(e){}}
function apply(reason){if(!cfg.enabled||runtime.interrupted)return;const d=new Date(),p=phaseAt(d),a=pickActivity(p.scene,d),wk=weatherKind();if(runtime.scene!==p.scene){runtime.scene=p.scene;log('scene',p.label,{weather:wk})}if(runtime.activity!==a){runtime.activity=a;log('activity',activityLabel(a),{weather:wk})}runtime.lastWeather=wk;if(g.SmPetEngine){g.SmPetEngine.setLifeScene(p.scene,a,{label:p.label,weather:wk,reason:reason||'tick'})}}
function activityLabel(a){return({sleep:'睡觉',stretch:'伸懒腰',lookaround:'看看四周',happy:'开心',wash:'洗脸',brush:'刷牙',eat:'吃饭',tea:'喝茶',coffee:'喝咖啡',walk:'散步',bike:'骑车',work:'工作',type:'打字',write:'写字',read:'读书',school:'上课',think:'思考',rest:'休息',yawn:'打哈欠',nap:'午睡',tv:'看电视',phone:'刷手机',web:'上网',bath:'洗澡',hike:'远足',swim:'戏水',umbrella:'撑伞',windy:'迎风',indoor:'室内休息',water:'喝水',hot_tea:'热茶',idle:'发呆'})[a]||a}
function arm(){clearTimeout(runtime.timer);if(!cfg.enabled||document.hidden)return;const interval=Math.max(15,Number(cfg.variationMinutes)||60)*60000;const now=Date.now();runtime.nextAt=Math.floor(now/interval)*interval+interval;runtime.timer=setTimeout(()=>{apply('interval');arm()},Math.min(runtime.nextAt-now,60000));}
function interrupt(kind,label){if(!cfg.enabled)return;runtime.interrupted={scene:runtime.scene,activity:runtime.activity,at:Date.now(),kind};if(g.SmPetEngine)g.SmPetEngine.setLifeScene('assist',kind,{label:label||'正在帮忙',interruption:true});}
function resume(){if(!runtime.interrupted)return;runtime.interrupted=null;setTimeout(()=>{apply('resume');arm()},600)}
function setConfig(patch){Object.assign(cfg,patch||{});if(!ROUTINES[cfg.routine])cfg.routine='worker';cfg.variationMinutes=Math.max(15,Math.min(240,Number(cfg.variationMinutes)||60));save();apply('settings');arm();bindControls()}
function fmtTime(t){const d=new Date(t);return d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}
function showDiary(){let m=document.getElementById('petLifeDiaryModal');if(!m){m=document.createElement('div');m.id='petLifeDiaryModal';m.className='pet-life-diary';m.innerHTML='<div class="pet-life-diary-card"><button class="pet-life-close" aria-label="关闭">×</button><h3>📔 萌宠养成日记</h3><div class="pet-life-diary-list"></div></div>';document.body.appendChild(m);m.querySelector('.pet-life-close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}const list=m.querySelector('.pet-life-diary-list'),a=diary().slice(-60).reverse();list.innerHTML=a.length?a.map(x=>`<div class="pet-diary-row"><time>${fmtTime(x.at)}</time><span>${escapeHtml(x.label)}</span>${x.meta&&x.meta.weather?`<small>${escapeHtml(x.meta.weather)}</small>`:''}</div>`).join(''):'<div class="settings-note">今天还没有生活记录。萌宠会随着真实时间自然留下轻量日记。</div>';m.classList.add('open')}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function bindControls(){const r=document.getElementById('petRoutine');if(r){r.value=cfg.routine;r.onchange=()=>setConfig({routine:r.value})}const v=document.getElementById('petLifeInterval');if(v){v.value=String(cfg.variationMinutes);v.onchange=()=>setConfig({variationMinutes:Number(v.value)})}const a=document.getElementById('petAvoidInputs');if(a){a.checked=cfg.avoidInputs;a.onchange=()=>setConfig({avoidInputs:a.checked})}const w=document.getElementById('petWeatherLink');if(w){w.checked=cfg.weather;w.onchange=()=>setConfig({weather:w.checked})}const d=document.getElementById('petDiaryEnabled');if(d){d.checked=cfg.diary;d.onchange=()=>setConfig({diary:d.checked})}const b=document.getElementById('petDiaryOpen');if(b)b.onclick=showDiary}
function safeMoveFor(el){if(!cfg.avoidInputs||!g.SmPetEngine||!el||!el.getBoundingClientRect)return;const r=el.getBoundingClientRect();if(r.width<4||r.height<4)return;g.SmPetEngine.avoidRect(r,{reason:'focus'})}
function bindAvoidance(){document.addEventListener('focusin',e=>{const el=e.target;if(el&&el.matches&&el.matches('input,textarea,select,[contenteditable="true"]'))safeMoveFor(el)},true);document.addEventListener('click',e=>{const el=e.target&&e.target.closest&&e.target.closest('button,.modal,.camera-view,.ocr-camera,#idphotoCameraView');if(el&&/camera|modal/i.test(String(el.className)+' '+String(el.id)))safeMoveFor(el)},true);const vv=g.visualViewport;if(vv)vv.addEventListener('resize',()=>{const el=document.activeElement;if(el&&el!==document.body)safeMoveFor(el)})}
function bind(){load();bindControls();bindAvoidance();document.addEventListener('visibilitychange',()=>{if(document.hidden)clearTimeout(runtime.timer);else{apply('foreground');arm()}});g.addEventListener('pageshow',()=>{apply('pageshow');arm()});setTimeout(()=>{apply('boot');arm()},150)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();
g.SmPetLifeOS={ROUTINES,MICRO,phaseAt,pickActivity,activityLabel,setConfig,getConfig:()=>Object.assign({},cfg),interrupt,resume,showDiary,getDiary:diary,apply,VERSION:1};
})(window);
