(function(g){'use strict';
const KEY='sm_pet_v1',animals=[['rat','鼠','🐭'],['ox','牛','🐮'],['tiger','虎','🐯'],['rabbit','兔','🐰'],['dragon','龙','🐲'],['snake','蛇','🐍'],['horse','马','🐴'],['goat','羊','🐑'],['monkey','猴','🐵'],['rooster','鸡','🐔'],['dog','狗','🐶'],['pig','猪','🐷']];
let state={enabled:true,pet:'dragon',activity:'normal'},timer=0;
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(e){}return state}function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function info(){return animals.find(a=>a[0]===state.pet)||animals[4]}
function render(){let p=document.getElementById('smDesktopPet');if(!p){p=document.createElement('button');p.id='smDesktopPet';p.className='sm-pet';p.type='button';p.innerHTML='<span class="sm-pet-face"></span><span class="sm-pet-bubble"></span>';document.body.appendChild(p);p.onclick=()=>react('happy','你好呀！')}p.hidden=!state.enabled;p.querySelector('.sm-pet-face').textContent=info()[2];p.dataset.pet=state.pet;p.dataset.activity=state.activity;document.querySelectorAll('[data-pet-choice]').forEach(b=>b.classList.toggle('active',b.dataset.petChoice===state.pet))}
function react(kind,text){if(!state.enabled)return;let p=document.getElementById('smDesktopPet');if(!p)return;p.dataset.state=kind||'idle';let b=p.querySelector('.sm-pet-bubble');if(text){b.textContent=text;b.classList.add('show');setTimeout(()=>b.classList.remove('show'),2600)}clearTimeout(timer);timer=setTimeout(()=>p.dataset.state='sleep',3000)}
function setPet(v){if(animals.some(a=>a[0]===v)){state.pet=v;save();render();react('happy','换好啦！')}}function setEnabled(v){state.enabled=!!v;save();render()}function setActivity(v){if(['quiet','normal','active'].includes(v)){state.activity=v;save();render()}}
function bind(){load();render();document.querySelectorAll('[data-pet-choice]').forEach(b=>b.onclick=()=>setPet(b.dataset.petChoice));let on=document.getElementById('petEnabled');if(on){on.checked=state.enabled;on.onchange=()=>setEnabled(on.checked)}let a=document.getElementById('petActivity');if(a){a.value=state.activity;a.onchange=()=>setActivity(a.value)}window.addEventListener('sm:reminder',e=>react('remind',(e.detail&&e.detail.text)||'有提醒啦！'));window.addEventListener('sm:ledger-saved',()=>react('happy','记好啦 ✓'));window.addEventListener('sm:recognition-start',()=>react('focus','我来帮你看'));document.addEventListener('visibilitychange',()=>{if(document.hidden){let p=document.getElementById('smDesktopPet');if(p)p.dataset.state='sleep'}})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind);else bind();g.SmPetEngine={animals,state,setPet,setEnabled,setActivity,react,VERSION:1};
})(window);