(function(g){'use strict';
  let stream=null,timer=null,stable=0,facing='user';
  const $=id=>document.getElementById(id);
  function spec(){return g.IDPhotoStudio&&g.IDPhotoStudio.currentSpec?g.IDPhotoStudio.currentSpec():null;}
  function guideGeometry(s){const head=Number(s&&s.headHeightRatio)||.46;return {headHeightRatio:Math.max(.32,Math.min(.62,head)),eyeRatio:Number(s&&s.eyeLineRatio)||.42};}
  function paintGuide(state='idle'){const cv=$('idpGuide'),v=$('idpLiveVideo');if(!cv||!v)return;const r=v.getBoundingClientRect(),dpr=devicePixelRatio||1;cv.width=Math.max(1,Math.round(r.width*dpr));cv.height=Math.max(1,Math.round(r.height*dpr));cv.style.width=r.width+'px';cv.style.height=r.height+'px';const x=cv.getContext('2d');x.scale(dpr,dpr);x.clearRect(0,0,r.width,r.height);const geo=guideGeometry(spec()),h=r.height*geo.headHeightRatio,w=h*.76,cx=r.width/2,cy=r.height*.43;x.save();x.strokeStyle=state==='ok'?'#22c55e':state==='warn'?'#f59e0b':'rgba(255,255,255,.92)';x.lineWidth=3;x.setLineDash([10,8]);x.beginPath();x.ellipse(cx,cy,w/2,h/2,0,0,Math.PI*2);x.stroke();x.setLineDash([]);x.globalAlpha=.65;x.beginPath();x.moveTo(cx-w*.85,cy+h*.62);x.quadraticCurveTo(cx,cy+h*.22,cx+w*.85,cy+h*.62);x.stroke();x.globalAlpha=.45;x.beginPath();x.moveTo(cx-w*.55,cy-h*.05);x.lineTo(cx+w*.55,cy-h*.05);x.stroke();x.restore();}
  async function analyze(){const v=$('idpLiveVideo'),msg=$('idpCoachMessage');if(!v||v.readyState<2)return;paintGuide('idle');if(!('FaceDetector'in g)){if(msg)msg.textContent='请将头部放入轮廓框；当前浏览器无实时人脸检测，拍摄后会再次检查。';return;}try{const fd=new FaceDetector({fastMode:true,maxDetectedFaces:2}),faces=await fd.detect(v);if(faces.length!==1){stable=0;if(msg)msg.textContent=faces.length>1?'只保留一人进入画面':'请把脸放入头像框';paintGuide('warn');return;}const b=faces[0].boundingBox,fh=b.height/v.videoHeight,cx=(b.x+b.width/2)/v.videoWidth,ideal=guideGeometry(spec()).headHeightRatio;let text='位置合适，请保持';let state='ok';if(fh>ideal*1.28){text='请稍微后退一些';state='warn';stable=0;}else if(fh<ideal*.72){text='请靠近一些';state='warn';stable=0;}else if(cx<.42){text='请向右一点';state='warn';stable=0;}else if(cx>.58){text='请向左一点';state='warn';stable=0;}else stable++;paintGuide(state);if(msg)msg.textContent=text+(stable>3?' ✓':'');}catch(e){if(msg)msg.textContent='实时检测暂不可用，请按头像框构图；拍摄后继续质量检查。';}}
  async function start(){await stop();const v=$('idpLiveVideo'),panel=$('idpLivePanel');if(!v||!navigator.mediaDevices?.getUserMedia)return false;stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing},width:{ideal:1280},height:{ideal:1600}},audio:false});v.srcObject=stream;panel.hidden=false;panel.dataset.facing=facing;await v.play();paintGuide();timer=setInterval(analyze,350);return true;}
  async function stop(){if(timer){clearInterval(timer);timer=null;}if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}const p=$('idpLivePanel');if(p)p.hidden=true;}
  function capture(){const v=$('idpLiveVideo');if(!v||!v.videoWidth)return null;const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return c;}
  async function switchCamera(){facing=facing==='user'?'environment':'user';return start();}
  g.IDPhotoCameraCoach={start,stop,capture,switchCamera,paintGuide,guideGeometry,VERSION:1};
})(window);
