(function(g){'use strict';
let sourceUrl='',lastQuality=null,lastCanvas=null,lastFace=null;const $=id=>document.getElementById(id);
function setStatus(t,type='info'){let e=$('idpStatus');if(e){e.textContent=t;e.dataset.type=type}}
function currentSpec(){let key=$('idpSpec')&&$('idpSpec').value;return g.IDPhotoSpecRegistry.list().find(x=>g.IDPhotoSpecRegistry.key(x)===key)||null}
function renderSpecs(){let s=$('idpSpec');if(!s||!g.IDPhotoSpecRegistry)return;s.innerHTML='';for(let x of g.IDPhotoSpecRegistry.list()){let o=document.createElement('option');o.value=g.IDPhotoSpecRegistry.key(x);o.textContent=x.label||x.documentType;s.appendChild(o)}s.onchange=()=>{updatePolicy();g.IDPhotoCameraCoach?.paintGuide();renderProcessed()}}
function updatePolicy(){let s=currentSpec(),e=$('idpPolicy');if(!e)return;let p=!s?'':s.retouchPolicy==='none'?'该参考类型默认禁止自动修饰；请加载官方规格包确认规则。':s.retouchPolicy==='limited'?'仅允许规则包明确许可的有限处理。':'允许本地基础光影/背景处理（最终仍以办理机构要求为准）。';e.textContent=p?'处理规则：'+p:''}
async function loadCanvas(c){lastCanvas=c;let img=$('idpPreview');img.src=c.toDataURL('image/jpeg',.94);await img.decode();let res=await g.IDPhotoCaptureQualityGate.analyzeImage(img,{minFacePx:420});lastQuality=res;lastFace=res.face||null;renderQuality(res);renderProcessed()}
async function loadFile(file){if(!file)return;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);let img=$('idpPreview');img.src=sourceUrl;await img.decode();setStatus('正在检查距离、有效人脸像素、模糊、多人、构图与光照…');lastCanvas=g.IDPhotoImageProcessor.canvasFromImage(img);let res=await g.IDPhotoCaptureQualityGate.analyzeImage(img,{minFacePx:420});lastQuality=res;lastFace=res.face||null;renderQuality(res);renderProcessed()}
function renderQuality(res){let box=$('idpQuality');if(!box)return;let cls=res.ok?'good':res.score>=60?'warn':'bad';box.className='idp-quality '+cls;box.innerHTML=`<strong>预计成片质量 ${Math.round(res.score)}/100</strong>${res.issues.length?'<ul>'+res.issues.map(x=>`<li>${x.message}</li>`).join('')+'</ul>':'<div>✓ 距离、构图、清晰度与光照基础检查通过</div>'}`;setStatus(res.ok?'基础质量检查通过，可继续制作':'请优先根据提示改善拍摄条件',res.ok?'ok':'warn')}
function renderProcessed(){if(!lastCanvas)return;let spec=currentSpec(),c=lastCanvas,policy=spec?.retouchPolicy||'normal',strength=Number(($('idpRelight')||{}).value||0)/100;if(policy!=='none'&&strength>0)c=g.IDPhotoImageProcessor.relight(c,strength,lastFace);let bg=($('idpBg')||{}).value||'original';if(policy==='normal'&&bg!=='original')c=g.IDPhotoImageProcessor.backgroundMatte(c,bg,Number(($('idpTolerance')||{}).value||44),28);if(spec?.widthMm&&spec?.heightMm)c=g.IDPhotoImageProcessor.cropToSpec(c,spec,lastFace);let out=$('idpProcessed');if(out){out.width=c.width;out.height=c.height;out.getContext('2d').drawImage(c,0,0)}return c}
async function downloadPhoto(){let c=renderProcessed();if(!c)return;let spec=currentSpec()||{},o=g.IDPhotoOutputProfiles?.read()||{format:'jpeg',quality:.92};let blob=await g.IDPhotoImageProcessor.encode(c,{format:o.format,quality:o.quality,targetKb:spec.targetKb,maxKb:spec.maxKb});if(!blob)return;let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='id-photo.'+(o.format==='png'?'png':'jpg');a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function printSheet(){let p=renderProcessed();if(!p)return;let o=g.IDPhotoOutputProfiles?.read()||{};let r=g.IDPhotoImageProcessor.makePrintSheet(p,{paper:o.paper,paperWidthMm:o.paperWidthMm,paperHeightMm:o.paperHeightMm,dpi:o.dpi,count:o.count,marginMm:o.marginMm,gapMm:o.gapMm,cropMarks:o.cropMarks});let blob=await new Promise(ok=>r.canvas.toBlob(ok,o.format==='png'?'image/png':'image/jpeg',o.quality||.95));let url=URL.createObjectURL(blob);open(url,'_blank');setStatus(`已按 ${r.paperMm[0].toFixed(1)}×${r.paperMm[1].toFixed(1)} mm / ${r.dpi} DPI 排版 ${r.placed} 张（最大 ${r.capacity} 张）。`,'ok');setTimeout(()=>URL.revokeObjectURL(url),60000)}
async function startCamera(){try{await g.IDPhotoCameraCoach.start();setStatus('请按规格头像框调整距离和位置；引导框不会写入最终照片。','ok')}catch(e){setStatus('无法打开实时相机：'+(e.message||e),'warn')}}
async function captureLive(){let c=g.IDPhotoCameraCoach.capture();if(!c)return setStatus('相机尚未准备好','warn');await loadCanvas(c);await g.IDPhotoCameraCoach.stop()}
function init(){renderSpecs();updatePolicy();['idpRelight','idpBg','idpTolerance'].forEach(id=>$(id)?.addEventListener('input',renderProcessed));$('idpFile')?.addEventListener('change',e=>loadFile(e.target.files?.[0]));$('idpCamera')?.addEventListener('change',e=>loadFile(e.target.files?.[0]));if($('idpImportBtn'))$('idpImportBtn').onclick=()=>$('idpFile')?.click();if($('idpStartCamera'))$('idpStartCamera').onclick=async()=>{if(!$('idpLivePanel').hidden)return captureLive();await startCamera();$('idpStartCamera').textContent='● 使用当前画面'};if($('idpStopCamera'))$('idpStopCamera').onclick=async()=>{await g.IDPhotoCameraCoach.stop();$('idpStartCamera').textContent='● 拍照'};if($('idpSwitchCamera'))$('idpSwitchCamera').onclick=()=>g.IDPhotoCameraCoach.switchCamera();if($('idpMoreBtn'))$('idpMoreBtn').onclick=()=>{$('idpMorePanel').hidden=!$('idpMorePanel').hidden};$('idpDownload').onclick=downloadPhoto;$('idpPrint').onclick=printSheet}
g.IDPhotoStudio={init,loadFile,renderProcessed,downloadPhoto,printSheet,currentSpec,VERSION:212};document.addEventListener('DOMContentLoaded',init);
})(window);
