(function(g){'use strict';
  let sourceUrl='',lastQuality=null,lastCanvas=null,lastFace=null;
  const $=id=>document.getElementById(id);
  function setStatus(text,type='info'){const e=$('idpStatus');if(!e)return;e.textContent=text;e.dataset.type=type;}
  function currentSpec(){const key=$('idpSpec')&&$('idpSpec').value;return g.IDPhotoSpecRegistry.list().find(x=>g.IDPhotoSpecRegistry.key(x)===key)||null;}
  function renderSpecs(){const s=$('idpSpec');if(!s||!g.IDPhotoSpecRegistry)return;s.innerHTML='';for(const x of g.IDPhotoSpecRegistry.list()){const o=document.createElement('option');o.value=g.IDPhotoSpecRegistry.key(x);o.textContent=x.label||x.documentType;s.appendChild(o);}s.onchange=()=>updatePolicy();}
  function updatePolicy(){const s=currentSpec(),e=$('idpPolicy');if(!e)return;if(!s){e.textContent='';return;}const p=s.retouchPolicy==='none'?'该参考类型默认禁止自动修饰；请加载官方规格包确认规则。':s.retouchPolicy==='limited'?'仅允许规则包明确许可的有限处理。':'允许本地基础光影/背景处理（最终仍以办理机构要求为准）。';e.textContent='处理规则：'+p;}
  async function loadFile(file){if(!file)return;if(sourceUrl)URL.revokeObjectURL(sourceUrl);sourceUrl=URL.createObjectURL(file);const img=$('idpPreview');img.src=sourceUrl;await img.decode();setStatus('正在检查距离、有效人脸像素、模糊、多人、构图与光照…');lastCanvas=g.IDPhotoImageProcessor.canvasFromImage(img);const res=await g.IDPhotoCaptureQualityGate.analyzeImage(img,{minFacePx:420});lastQuality=res;lastFace=res.face||null;renderQuality(res);renderProcessed();}
  function renderQuality(res){const box=$('idpQuality');if(!box)return;const cls=res.ok?'good':res.score>=60?'warn':'bad';box.className='idp-quality '+cls;box.innerHTML=`<strong>预计成片质量 ${Math.round(res.score)}/100</strong>${res.issues.length?'<ul>'+res.issues.map(x=>`<li>${x.message}</li>`).join(''):'<div>✓ 距离、构图、清晰度与光照基础检查通过</div>'}`;setStatus(res.ok?'基础质量检查通过，可继续制作':'请优先根据提示改善拍摄条件',res.ok?'ok':'warn');}
  function renderProcessed(){if(!lastCanvas)return;const spec=currentSpec();let c=lastCanvas;const policy=spec&&spec.retouchPolicy||'normal';const strength=Number(($('idpRelight')||{}).value||0)/100;if(policy!=='none'&&strength>0)c=g.IDPhotoImageProcessor.relight(c,strength);const bg=($('idpBg')||{}).value||'original';if(policy==='normal'&&bg!=='original')c=g.IDPhotoImageProcessor.backgroundMatte(c,bg,Number(($('idpTolerance')||{}).value||44),28);if(spec&&spec.widthMm&&spec.heightMm)c=g.IDPhotoImageProcessor.cropToSpec(c,spec,lastFace);const out=$('idpProcessed');if(out){out.width=c.width;out.height=c.height;const x=out.getContext('2d');x.clearRect(0,0,out.width,out.height);x.drawImage(c,0,0);}return c;}
  async function downloadPhoto(){const c=renderProcessed();if(!c)return;const spec=currentSpec()||{};const blob=await g.IDPhotoImageProcessor.toJpegTargetKb(c,spec.targetKb,spec.maxKb);if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='id-photo.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  async function printSheet(){const p=renderProcessed();if(!p)return;const paper=($('idpPaper')||{}).value||'4x6',count=Number(($('idpCount')||{}).value||8);const r=g.IDPhotoImageProcessor.makePrintSheet(p,{paper,count});const blob=await new Promise(ok=>r.canvas.toBlob(ok,'image/jpeg',.95));const url=URL.createObjectURL(blob),w=open(url,'_blank');setStatus(`已排版 ${r.placed} 张；新窗口可打印或保存。`,'ok');setTimeout(()=>URL.revokeObjectURL(url),60000);return w;}
  function init(){renderSpecs();updatePolicy();for(const id of ['idpRelight','idpBg','idpTolerance']){const e=$(id);if(e)e.addEventListener('input',renderProcessed);}const input=$('idpFile');if(input)input.addEventListener('change',e=>loadFile(e.target.files&&e.target.files[0]));const cam=$('idpCamera');if(cam)cam.addEventListener('change',e=>loadFile(e.target.files&&e.target.files[0]));const dl=$('idpDownload');if(dl)dl.onclick=downloadPhoto;const pr=$('idpPrint');if(pr)pr.onclick=printSheet;}
  g.IDPhotoStudio={init,loadFile,renderProcessed,downloadPhoto,printSheet};document.addEventListener('DOMContentLoaded',init);
})(window);
